// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OUoaZ2I7vn7epzBcW4Mpo81In-kdv6E',
    appId: '1:841132008055:web:default',
    messagingSenderId: '841132008055',
    projectId: 'ganaderia-7abb8',
    authDomain: 'ganaderia-7abb8.firebaseapp.com',
    storageBucket: 'ganaderia-7abb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OUoaZ2I7vn7epzBcW4Mpo81In-kdv6E',
    appId: '1:841132008055:android:e1587bec1af56c133fdc72',
    messagingSenderId: '841132008055',
    projectId: 'ganaderia-7abb8',
    storageBucket: 'ganaderia-7abb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '841132008055',
    projectId: 'ganaderia-7abb8',
    storageBucket: 'ganaderia-7abb8.firebasestorage.app',
    iosBundleId: 'com.example.ganaderia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '841132008055',
    projectId: 'ganaderia-7abb8',
    storageBucket: 'ganaderia-7abb8.firebasestorage.app',
    iosBundleId: 'com.example.ganaderia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5OUoaZ2I7vn7epzBcW4Mpo81In-kdv6E',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '841132008055',
    projectId: 'ganaderia-7abb8',
    storageBucket: 'ganaderia-7abb8.firebasestorage.app',
  );
}






